version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: railway
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 6eD*E5EAeAge25-1AD-AEdCgA*c5-f6f
    ports:
      - "13803:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
