# Generated by Django 5.0.1 on 2024-02-06 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='CustomUser',
        # ),
        # migrations.RemoveField(
        #     model_name='paragraphword',
        #     name='paragraph',
        # ),
        # migrations.RemoveField(
        #     model_name='paragraphword',
        #     name='word',
        # ),
        # migrations.DeleteModel(
        #     name='Paragraph',
        # ),
        # migrations.DeleteModel(
        #     name='ParagraphWord',
        # ),
        # migrations.DeleteModel(
        #     name='Word',
        # ),
    ]
